### ISSUE TITLE
视频界面 评论区消失  右侧视频推荐不加载

### ISSUE THREAD

**Issue by talking-toaster** [the1812/Bilibili-Evolved#1081]
**关于哪一项功能**
无法确定是哪一项功能导致

**问题描述**

视频无关，最近几天未更改设置，网络良好
我的设置：
[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/5450245/bilibili-evolved-settings.zip)

**脚本版本**

Stable v1.11.0
内容包: caf5ffa

**浏览器版本**

Chrome 85.0.4183.83（正式版本） （64 位）

**错误信息**

```
s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7

Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:57317)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60655)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60590)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:61055)
    at a.t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:34369)
```
**附加截图**
![image](https://user-images.githubusercontent.com/49156890/97405263-592b4800-1932-11eb-8e2f-fa8811fd4df1.png)
![image](https://user-images.githubusercontent.com/49156890/97405345-74965300-1932-11eb-9c24-96376063a29a.png)

**Comment by Coulomb-G** [comment]
Duplicate of #1076
