### ISSUE TITLE
分P视频标题消失

### ISSUE THREAD

**Issue by Lin-XCC** [the1812/Bilibili-Evolved#1118]
**关于哪一项功能**
视频播放相关

**问题描述**

如果视频是分P视频，启用脚本后分P标题消失为空白

**脚本版本**

v1.11.0

**浏览器版本**

 85.0.4183.83

**错误信息**

stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:57317)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60655)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60590)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:61055)
    at a.t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:34369)
hn.get @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
hn @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
Tn.$mount @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
Tn.$mount @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:46
fo.onReady @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:46
So.onReady @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:46
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:46
n @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:1
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:32
n @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:1
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:1
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:1

**附加截图**
![QQ截图20201029085602](https://user-images.githubusercontent.com/52395718/97512527-b40d7f80-19c4-11eb-8f84-a5a5967d1cf9.jpg)

**Comment by Geeyun-JY3** [comment]
看！
置！
顶！
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
