### ISSUE TITLE
评论区显示问题

### ISSUE THREAD

**Issue by guaner12** [the1812/Bilibili-Evolved#1140]
**关于哪一项功能**
评论区不不见了

**问题描述**

所有视频的评论区都没有了

**脚本版本**

Stable v1.11.0

**浏览器版本**

版本 86.0.4240.111（正式版本） （64 位）

**错误信息**

Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:57317)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:60655)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:60590)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:61055)
    at a.t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.4e68f5ed27f80c8fb3764be4bf2f5bbb28148fae.js:7:34369)

Failed to load resource: the server responded with a status of 403 ()
cn-sdyt-cu-v-11.bilivideo.com/upgcxcode/30/75/250797530/250797530-1-30080.m4s?expires=1604028595&platform=pc&ssig=GGFEYqe5IN1bpp2k_h6CCA&oi=2362416634&trid=0696b1e3fcc84a0f92fdf5bff0a6879bu&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&cdnid=9568&mid=340407356&orderid=1,3&agrr=1&logo=40000000:1 Failed to load resource: the server responded with a status of 403 ()
upos-sz-mirrorhw.bilivideo.com/upgcxcode/30/75/250797530/250797530-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1604028595&gen=playurl&os=hwbv&oi=2362416634&trid=0696b1e3fcc84a0f92fdf5bff0a6879bu&platform=pc&upsig=9ffd5d7b142e9f73cc211ba1969b4e13&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=340407356&orderid=2,3&agrr=1&logo=40000000:1 Failed to load resource: the server responded with a status of 403 ()
cn-sdjn2-cu-v-06.bilivideo.com/upgcxcode/30/75/250797530/250797530-1-30080.m4s?expires=1604028595&platform=pc&ssig=GGFEYqe5IN1bpp2k_h6CCA&oi=2362416634&trid=0696b1e3fcc84a0f92fdf5bff0a6879bu&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&cdnid=8173&mid=340407356&orderid=0,3&agrr=1&logo=80000000:1 Failed to load resource: the server responded with a status of 403 ()

**附加截图**
![image](https://user-images.githubusercontent.com/64568382/97698953-583a1800-1ae4-11eb-80bf-f5021ee45072.png)

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
