### ISSUE TITLE
“动态首页”页面的评论区无法加载

### ISSUE THREAD

**Issue by chenxi-Eumenides** [the1812/Bilibili-Evolved#1924]
“动态首页”页面的评论区无法加载

出现时间:2021.6.9 (7号没问题，8号忘了有没有看，应该也是没问题的)

控制台报错:
comment.min.js:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '[object HTMLDivElement]' is not a valid selector.
    at x._identity (https://s1.hdslb.com/bfs/seed/jinkela/commentpc/comment.min.js:1:172377)
    at x._createListCon (https://s1.hdslb.com/bfs/seed/jinkela/commentpc/comment.min.js:1:161745)
    at x._createReplyItem (https://s1.hdslb.com/bfs/seed/jinkela/commentpc/comment.min.js:1:159221)
    at x._renderReplyList (https://s1.hdslb.com/bfs/seed/jinkela/commentpc/comment.min.js:1:158315)
    at x._updateReplyListByData (https://s1.hdslb.com/bfs/seed/jinkela/commentpc/comment.min.js:1:156466)
    at Object.<anonymous> (https://s1.hdslb.com/bfs/seed/jinkela/commentpc/comment.min.js:1:153182)
    at o (https://static.hdslb.com/js/jquery.min.js:2:14733)
    at Object.fireWith [as resolveWith] (https://static.hdslb.com/js/jquery.min.js:2:15502)
    at w (https://static.hdslb.com/js/jquery.min.js:4:12472)
    at HTMLScriptElement.d.onload.d.onreadystatechange (https://static.hdslb.com/js/jquery.min.js:4:17063)

截图:
![image](https://user-images.githubusercontent.com/76398980/121293274-f2392d00-c91d-11eb-8261-63b01ccb9962.png)

Stable v1.12.8 内容包: 9ce5eca
chrome v91.0.4472.77

**Comment by Coulomb-G** [comment]
b站日常炸了而已,你把脚本关了也一样

**Comment by chenxi-Eumenides** [comment]
> b站日常
> 炸了伤，你把脚本关了也一样现在已经好了，刷新看看

啊这，我几分钟后好了，刚想删这个反馈
