### ISSUE TITLE
默认播放器模式 在特定情况下不会正确应用（即使勾选了播放时应用）。

### ISSUE THREAD

**Issue by Winston-62** [the1812/Bilibili-Evolved#2882]
### 关于哪一项功能

默认播放器模式

### 问题描述

在以后台标签页的方式打开多个链接后能明显感觉到加载存在卡顿（关闭脚本则无此问题），并且将后台标签页切换到前台播放时不会应用全屏

### 脚本版本

2.0.8

### 浏览器版本

Chrome  版本 97.0.4692.71（正式版本） （64 位）

### 错误信息

```shell
9Unchecked runtime.lastError: The message port closed before a response was received.
null:1 Failed to load resource: the server responded with a status of 404 ()
Bilibili Evolved.user.js:227 window._ is deprecated, please use window.lodash instead.
get @ Bilibili Evolved.user.js:227
BV1eu41127J9:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://cdn.jsdelivr.net/gh/Templarian/MaterialDesign-Webfont@5.3.45/fonts/materialdesignicons-webfont.woff2?v=5.3.45
sentry-5.7.1.min.js:2 Error: timeout
    at bili-header.umd.js:24:45610
    at sentryWrapped (sentry-5.7.1.min.js:2:37371)
(anonymous) @ sentry-5.7.1.min.js:2
nc-loader-1.10.0.min.js:2 WebSocket connection to 'wss://web-player-tracker.biliapi.net/socket.io/?buvid=00A2BFA3-A4CF-409E-9510-B2E91A50EE67184993infoc&sdkVersion=1.10.0-9ab1466&aid=508072293&cid=483192392&duration=167&EIO=4&transport=websocket' failed: 
doOpen @ nc-loader-1.10.0.min.js:2
nc-loader-1.10.0.min.js:2 WebSocket connection to 'wss://web-player-tracker.biliapi.net/socket.io/?buvid=00A2BFA3-A4CF-409E-9510-B2E91A50EE67184993infoc&sdkVersion=1.10.0-9ab1466&aid=508072293&cid=483192392&duration=167&EIO=4&transport=websocket' failed: 
doOpen @ nc-loader-1.10.0.min.js:2
sentry-5.7.1.min.js:2 requestedPopup false
nc-loader-1.10.0.min.js:2 WebSocket connection to 'wss://web-player-tracker.biliapi.net/socket.io/?buvid=00A2BFA3-A4CF-409E-9510-B2E91A50EE67184993infoc&sdkVersion=1.10.0-9ab1466&aid=508072293&cid=483192392&duration=167&EIO=4&transport=websocket' failed: 
doOpen @ nc-loader-1.10.0.min.js:2
sentry-5.7.1.min.js:2 requestedPopup true
sentry-5.7.1.min.js:2 requestedPopup false
sentry-5.7.1.min.js:2 requestedPopup true
nc-loader-1.10.0.min.js:2 WebSocket connection to 'wss://web-player-tracker.biliapi.net/socket.io/?buvid=00A2BFA3-A4CF-409E-9510-B2E91A50EE67184993infoc&sdkVersion=1.10.0-9ab1466&aid=508072293&cid=483192392&duration=167&EIO=4&transport=websocket' failed: 
doOpen @ nc-loader-1.10.0.min.js:2
```

**Comment by FoundTheWOUT** [comment]
#2815
