### ISSUE TITLE
默认播放模式随机失效

### ISSUE THREAD

**Issue by jiang-yuan** [the1812/Bilibili-Evolved#2903]
### 关于哪一项功能

默认播放模式

### 问题描述

我也来反馈一下,我用的edge,默认播放模式是时灵时不灵,不针对特定视频。老问题了，1.0的evolved就会这样.
有时会宽屏有时不会,经常要手动点,头疼,看下图就是没生效.
![image](https://user-images.githubusercontent.com/36291537/149965951-f22dfe40-d45d-4fe7-9243-7eaba9680144.png)
有点怀疑是不是油猴脚本加载的优先级太低,进页面的时候如果视频已经太快自动播放了,脚本就会操作设置播放模式失败
![image](https://user-images.githubusercontent.com/36291537/149966185-5c348aee-237d-4aaa-99b2-0557146ab0a9.png)
![image](https://user-images.githubusercontent.com/36291537/149966258-17088fa9-9d00-46de-8e31-2239fc62fd15.png)

### 脚本版本

v2.0.8-13-g93accf2ac

### 浏览器版本

Microsoft Edge 版本 97.0.1072.62 (官方内部版本) (64 位)

### 播放器版本

2.73.1

### 是否开启 HEVC

禁止 HEVC

### 错误信息

```shell
引擎快捷跳转 --- 开始执行 --- 发布者: qxin --- GitHub:https://github.com/qxinGitHub/searchEngineJump ← 问题反馈地址
视频网页全屏.user.js:65 [2022-01-18 23:22:08][Maximize Video] > Ready
Bilibili Evolved.user.js:227 
        
       window._ is deprecated, please use window.lodash instead.
get @ Bilibili Evolved.user.js:227
content-script.js:29 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findEntry')
    at content-script.js:29:127631
    at content-script.js:29:127719
    at lE (content-script.js:29:127981)
    at zE (content-script.js:29:135844)
    at content-script.js:29:156381
/video/BV1UF411v7Gb?spm_id_from=333.851.b_7265636f6d6d656e64.2:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
视频网页全屏.user.js:65 [2022-01-18 23:22:12][Maximize Video] > Ready
nc-loader-1.10.0.min.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-1.10.0.min.js:2:202073)
    at he.window (nc-loader-1.10.0.min.js:2:222176)
    at Module.<anonymous> (nc-loader-1.10.0.min.js:2:222944)
    at r (nc-loader-1.10.0.min.js:2:146)
    at Object.<anonymous> (nc-loader-1.10.0.min.js:2:85991)
    at r (nc-loader-1.10.0.min.js:2:146)
    at nc-loader-1.10.0.min.js:2:945
    at t (nc-loader-1.10.0.min.js:2:955)
    at nc-loader-1.10.0.min.js:2:226362
​ 脚本: 搜索引擎快捷跳转 --- 开始执行 --- 发布者: qxin --- GitHub:https://github.com/qxinGitHub/searchEngineJump ← 问题反馈地址
视频网页全屏.user.js:65 [2022-01-18 23:22:14][Maximize Video] > Ready
jsc-player.855c19c0.js:399 
        
       WebSocket connection to 'wss://broadcast.chat.bilibili.com:7826/sub?platform=web' failed: WebSocket is closed before the connection is established.
i.close @ jsc-player.855c19c0.js:399
2nc-loader-1.10.0.min.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-1.10.0.min.js:2:202073)
    at he.window (nc-loader-1.10.0.min.js:2:222176)
    at Module.<anonymous> (nc-loader-1.10.0.min.js:2:222944)
    at r (nc-loader-1.10.0.min.js:2:146)
    at Object.<anonymous> (nc-loader-1.10.0.min.js:2:85991)
    at r (nc-loader-1.10.0.min.js:2:146)
    at nc-loader-1.10.0.min.js:2:945
    at t (nc-loader-1.10.0.min.js:2:955)
    at nc-loader-1.10.0.min.js:2:226362
sentry-5.7.1.min.js:2 requestedPopup true
sentry-5.7.1.min.js:2 requestedPopup false
sentry-5.7.1.min.js:2 requestedPopup true
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 nextPage get Array(20)
sentry-5.7.1.min.js:2 requestedPopup false
sentry-5.7.1.min.js:2 requestedPopup true
sentry-5.7.1.min.js:2 requestedPopup false
sentry-5.7.1.min.js:2 requestedPopup true
6sentry-5.7.1.min.js:2 requestedPopup false
```

**Comment by timongh** [comment]
找到了比较稳定的复现方式（但也可能复现失败）：
1. 在脚本本体的通用设置中将“功能加载模式”设为“同时”
2. 在调试控制台中将网速限制为“慢速3G“（Chrome浏览器，其他浏览器类似。网速要够慢）

**Comment by timongh** [comment]
经过打日志发现（断点不行，断点会让问题无法复现）：问题出在对 `src/core/utils/index.ts` 中的 playerReady 的调用上。在该问题成功复现的情况下，该函数会卡住，无法结束。

具体到其源码，就是卡在了 unsafeWindow.onLoginInfoLoaded 上——传递给其的 resole 没有被调用。未被调用的原因暂未发现。

**Comment by timongh** [comment]
暂时没想到通用的解决方法。

在普通的视频页面下，或许可以试试用 player 来等待播放器加载（未尝试）：

```typescript
unsafeWindow.player.addEventListener(
  unsafeWindow.bPlayer.events.playerLoaded,
  () => { /* ... */ },
)
```

但是番剧页面没有这个 API。
