### ISSUE TITLE
网址参数清理需要例外

### ISSUE THREAD

**Issue by SetoKaiba** [the1812/Bilibili-Evolved#2953]
### 关于哪一项功能

网址参数清理

### 问题描述

网址参数清理需要例外，比如说打开
https://live.bilibili.com/5619408
然后点击热门榜，如果在网址参数清理打开的情况下，会造成无法切换榜单，关闭网址参数清理后就可以切换榜单了，应该是切换榜单利用的query参数，然后参数被清理了因此无法切换了吧，所以需要例外。

### 脚本版本

v2.1.2-3-g28f22f84f

### 浏览器版本

版本 99.0.4840.0（正式版本）dev （64 位）

### 错误信息

```shell
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
bilibili.f396460be18c50544abe.js:2 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
main.js:371 购物党隐私说明（键入disable_gwd_privacy()不再显示本声明）：
main.js:372     我们不会收集用户个人隐私信息，只会收集一些简单的产品交互行为，帮助改善产品，例如记录某个模块点击次数，更多信息请关注：
main.js:373 隐私协议: https://www.gwdang.com/static_page/privacy_policy.html
room-player.min.js:29 fMp4Player v1.37
chrome.js:48085 Uncaught DOMException: Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported. See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.
    at DynamicDetails.getWebRTCIP (chrome-extension://jgphnjokjhjlcnnajmfjlacjnjkhleah/js/chrome.js:48085:15)
    at collectMovement (chrome-extension://jgphnjokjhjlcnnajmfjlacjnjkhleah/js/chrome.js:48209:11)
    at chrome-extension://jgphnjokjhjlcnnajmfjlacjnjkhleah/js/chrome.js:64745:7
room-player.min.js:29 Chrome verion: 100
room-player.min.js:29 seek to: 15105.333/15273.089s, pos=3924188632
179.82b8e7031670229b0f5c.js:2 Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2022 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
179.82b8e7031670229b0f5c.js:2 Version: V4.0.0 "Life Experience", CodeName: Neptune.
chrome.js:21532 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
chrome.js:21543 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
​ load script start
userscript.html?name=BiliBili%E7%9B%B4%E6%92%AD%E9%97%B4%E8%A7%A3%E9%99%A4%E5%AD%97%E6%95%B0%E9%99%90%E5%88%B6.user.js&id=a640079e-9d39-4d26-bfbf-ae92cc615376:12169 ###绑定！
userscript.html?name=Bilibili%20Evolved.user.js&id=8084a033-2534-4816-b655-e0dae62b34d1:194 live watch
5619408:1 Unchecked runtime.lastError: The message port closed before a response was received.
VM6842:12 activated matchMedal (210949)
room-player.min.js:29 fMp4Player v1.37
room-player.min.js:29 seek to: 0/20416.398s, pos=74476
179.82b8e7031670229b0f5c.js:2 Danmaku Websocket Retry . 1
console.error @ 179.82b8e7031670229b0f5c.js:2
userscript.html?name=Bilibili%20Evolved.user.js&id=8084a033-2534-4816-b655-e0dae62b34d1:228 updated widgets Array(2)
```

**Comment by SetoKaiba** [comment]
大乱斗的也需要例外，不然大乱斗里面的查看赛季记录什么的也是不能用了。
//live.bilibili.com/activity/live-activity-battle/index.html?app_name=chaos&is_live_half_webview=1&hybrid_rotate_d=1&hybrid_half_ui=1,3,100p,70p,a27af6,0,30,100;2,2,375,100p,a27af6,0,30,100;3,3,100p,70p,a27af6,0,30,100;4,2,375,100p,a27af6,0,30,100;5,3,100p,70p,a27af6,0,30,100;6,3,100p,70p,a27af6,0,30,100;7,3,100p,70p,a27af6,0,30,100;8,3,100p,70p,a27af6,0,30,100&room_id=5619408&uid=178241268#/

**Comment by SetoKaiba** [comment]
@the1812

**Comment by SetoKaiba** [comment]
@the1812 有没有办法做到iframe里的都例外，因为我发现出问题的都是iframe里的，外面的地址清理就好了。

**Comment by the1812** [comment]
可以啊
