### ISSUE TITLE
组件设置无法保存以及组件无法删除

### ISSUE THREAD

**Issue by fantuyuan** [the1812/Bilibili-Evolved#2954]
### 关于哪一项功能

组件

### 问题描述

1. 组件开关及选项开关在刷新页面后无法保存更改结果。
2. 组件点击删除后再刷新页面依旧存在，无法删除。

### 脚本版本

v2.1.2-3-g28f22f84f

### 浏览器版本

Microsoft Edge 版本 97.0.1072.76 (官方内部版本) (64 位)

### 播放器版本

HTML5播放器 V2.73.7-a306a712

### 错误信息

```shell
解除B站区域限制.user.js:247 info: mode: default blocked_vip: undefined server: https://www.biliplus.com upos_server: undefined flv_prefer_ws:  remove_pre_ad: undefined enable_in_av: undefined readyState: loading isLogin: false isLoginBiliBili: true
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAABCAYAAACsXeyTAAAACXBIW%E2%80%A6sTAAALEwEAmpwYAAAAFUlEQVQIHWNIS0sr/v//PwMMDzY+ADqMahlW4J91AAAAAElFTkSuQmCC:1 
        
       Failed to load resource: net::ERR_INVALID_URL
Bilibili Evolved.user.js:189 [自动更新器] 开始检查更新
Bilibili Evolved.user.js:189 [downloadVideo] 未超过更新间隔期, 已跳过
[downloadSubtitle] 未超过更新间隔期, 已跳过
[downloadDanmaku] 未超过更新间隔期, 已跳过
[downloadAudio] 未超过更新间隔期, 已跳过
[downloadLiveRecords] 未超过更新间隔期, 已跳过
[extendFeedsLive] 未超过更新间隔期, 已跳过
[copyFeedsLink] 未超过更新间隔期, 已跳过
[disableFeedsDetails] 未超过更新间隔期, 已跳过
[feedsFilter] 未超过更新间隔期, 已跳过
[fixedFeedsSidebars] 未超过更新间隔期, 已跳过
[foldComments] 未超过更新间隔期, 已跳过
[fullFeedsContent] 未超过更新间隔期, 已跳过
[fullFeedsTitle] 未超过更新间隔期, 已跳过
[unfoldFeeds] 未超过更新间隔期, 已跳过
[liveAutoDraw] 未超过更新间隔期, 已跳过
[badgeHelper] 未超过更新间隔期, 已跳过
[liveDanmakuSendbar] 未超过更新间隔期, 已跳过
[liveHomeMute] 未超过更新间隔期, 已跳过
[dpiLiveShowgirl] 未超过更新间隔期, 已跳过
[alwaysShowDuration] 未超过更新间隔期, 已跳过
[customNavbar] 已更新组件'自定义顶栏', 刷新后生效
[hideRecommendedLive] 未超过更新间隔期, 已跳过
[simplifyLiveroom] 未超过更新间隔期, 已跳过
[columnUnlock] 未超过更新间隔期, 已跳过
[copyCommentsLink] 未超过更新间隔期, 已跳过
[imageExporter] 未超过更新间隔期, 已跳过
[imageResolution] 未超过更新间隔期, 已跳过
[urlParamsClean] 未超过更新间隔期, 已跳过
[viewCover] 已更新组件'查看封面', 刷新后生效
[darkModeFollowSystem] 已更新组件'夜间模式跟随系统', 刷新后生效
[darkMode] 已更新组件'夜间模式', 刷新后生效
[watchlaterRedirect] 已更新组件'稍后再看重定向', 刷新后生效
[bvidConvert] 已更新组件'BV 号转换', 刷新后生效
[danmakuAirborne] 已更新组件'启用弹幕空降', 刷新后生效
[fullVideoDescription] 已更新组件'展开视频简介', 刷新后生效
[outerWatchlater] 已更新组件'外置稍后再看', 刷新后生效
[doubleClickFullscreen] 已更新组件'双击全屏', 刷新后生效
[playerIntersectionActions] 已更新组件'播放器位置动作', 刷新后生效
[legacyAutoPlay] 已更新组件'传统连播模式', 刷新后生效
[removePlayerPopup] 已更新组件'删除视频弹窗', 刷新后生效
[videoScreenshot] 已更新组件'启用视频截图', 刷新后生效
[seekByFrames] 已更新组件'启用逐帧调整', 刷新后生效
[showCoverBeforePlay] 已更新组件'播放前显示封面', 刷新后生效
[skipChargeList] 已更新组件'跳过充电鸣谢', 刷新后生效
[quickFavorite] 已更新组件'启用快速收藏', 刷新后生效
[seoRedirect] 已更新组件'SEO 页面重定向', 刷新后生效
[videoCurTime] 已更新组件'视频内显示时间', 刷新后生效
[playerControlBackground] 已更新组件'播放器控制栏背景色', 刷新后生效
[defaultPlayerMode] 已更新组件'默认播放器模式', 刷新后生效
[biliplusRedirect] 已更新组件'BiliPlus 跳转支持', 刷新后生效
Bilibili Evolved.user.js:189 [launchBar.trendingSearch] 已更新插件'搜索栏 - 搜索推荐', 刷新后生效
[settingsPanel.tagFilters.recentComponents] 已更新插件'设置面板 - "最近使用" 类别', 刷新后生效
[customNavbar.items.darkMode] 已更新插件'自定义顶栏 - 夜间模式开关', 刷新后生效
[keymap.actions.darkMode] 已更新插件'快捷键扩展 - 夜间模式', 刷新后生效
[downloadVideo.outputs.aria2] 已更新插件'下载视频 - aria2 输出支持', 刷新后生效
[downloadVideo.outputs.idm] 已更新插件'下载视频 - IDM 输出支持', 刷新后生效
[downloadVideo.outputs.mpv] 已更新插件'下载视频 - MPV 输出支持', 刷新后生效
Bilibili Evolved.user.js:189 暂无样式更新
Bilibili Evolved.user.js:189 [自动更新器] 完成更新检查
BV15Y411t7dy:1 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
/images/base/error.png:1 
        
       Failed to load resource: the server responded with a status of 404 ()
/images/base/icons.png:1 
        
       Failed to load resource: the server responded with a status of 404 ()
nc-loader-1.10.0.min.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:202073)
    at he.window (s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:222176)
    at Module.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:222944)
    at r (s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:146)
    at Object.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:85991)
    at r (s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:146)
    at s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:945
    at t (s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:955)
    at s1.hdslb.com/bfs/static/nc/nc-loader-1.10.0.min.js:2:226362
I @ nc-loader-1.10.0.min.js:2
he.window @ nc-loader-1.10.0.min.js:2
(匿名) @ nc-loader-1.10.0.min.js:2
r @ nc-loader-1.10.0.min.js:2
(匿名) @ nc-loader-1.10.0.min.js:2
r @ nc-loader-1.10.0.min.js:2
(匿名) @ nc-loader-1.10.0.min.js:2
t @ nc-loader-1.10.0.min.js:2
(匿名) @ nc-loader-1.10.0.min.js:2
Bilibili Evolved.user.js:189 [自动更新器] 开始检查更新
Bilibili Evolved.user.js:189 [downloadVideo] 未超过更新间隔期, 已跳过
[downloadSubtitle] 未超过更新间隔期, 已跳过
[downloadDanmaku] 未超过更新间隔期, 已跳过
[downloadAudio] 未超过更新间隔期, 已跳过
[downloadLiveRecords] 未超过更新间隔期, 已跳过
[extendFeedsLive] 未超过更新间隔期, 已跳过
[copyFeedsLink] 未超过更新间隔期, 已跳过
[disableFeedsDetails] 未超过更新间隔期, 已跳过
[feedsFilter] 未超过更新间隔期, 已跳过
[fixedFeedsSidebars] 未超过更新间隔期, 已跳过
[foldComments] 未超过更新间隔期, 已跳过
[fullFeedsContent] 未超过更新间隔期, 已跳过
[fullFeedsTitle] 未超过更新间隔期, 已跳过
[unfoldFeeds] 未超过更新间隔期, 已跳过
[liveAutoDraw] 未超过更新间隔期, 已跳过
[badgeHelper] 未超过更新间隔期, 已跳过
[liveDanmakuSendbar] 未超过更新间隔期, 已跳过
[liveHomeMute] 未超过更新间隔期, 已跳过
[dpiLiveShowgirl] 未超过更新间隔期, 已跳过
[alwaysShowDuration] 未超过更新间隔期, 已跳过
[customNavbar] 已更新组件'自定义顶栏', 刷新后生效
[hideRecommendedLive] 未超过更新间隔期, 已跳过
[simplifyLiveroom] 未超过更新间隔期, 已跳过
[columnUnlock] 未超过更新间隔期, 已跳过
[copyCommentsLink] 未超过更新间隔期, 已跳过
[imageExporter] 未超过更新间隔期, 已跳过
[imageResolution] 未超过更新间隔期, 已跳过
[urlParamsClean] 未超过更新间隔期, 已跳过
[viewCover] 已更新组件'查看封面', 刷新后生效
[darkModeFollowSystem] 已更新组件'夜间模式跟随系统', 刷新后生效
[darkMode] 已更新组件'夜间模式', 刷新后生效
[watchlaterRedirect] 已更新组件'稍后再看重定向', 刷新后生效
[bvidConvert] 已更新组件'BV 号转换', 刷新后生效
[danmakuAirborne] 已更新组件'启用弹幕空降', 刷新后生效
[fullVideoDescription] 已更新组件'展开视频简介', 刷新后生效
[outerWatchlater] 已更新组件'外置稍后再看', 刷新后生效
[doubleClickFullscreen] 已更新组件'双击全屏', 刷新后生效
[playerIntersectionActions] 已更新组件'播放器位置动作', 刷新后生效
[legacyAutoPlay] 已更新组件'传统连播模式', 刷新后生效
[removePlayerPopup] 已更新组件'删除视频弹窗', 刷新后生效
[videoScreenshot] 已更新组件'启用视频截图', 刷新后生效
[seekByFrames] 已更新组件'启用逐帧调整', 刷新后生效
[showCoverBeforePlay] 已更新组件'播放前显示封面', 刷新后生效
[skipChargeList] 已更新组件'跳过充电鸣谢', 刷新后生效
[quickFavorite] 已更新组件'启用快速收藏', 刷新后生效
[seoRedirect] 已更新组件'SEO 页面重定向', 刷新后生效
[videoCurTime] 已更新组件'视频内显示时间', 刷新后生效
[playerControlBackground] 已更新组件'播放器控制栏背景色', 刷新后生效
[defaultPlayerMode] 已更新组件'默认播放器模式', 刷新后生效
[biliplusRedirect] 已更新组件'BiliPlus 跳转支持', 刷新后生效
Bilibili Evolved.user.js:189 [launchBar.trendingSearch] 已更新插件'搜索栏 - 搜索推荐', 刷新后生效
[settingsPanel.tagFilters.recentComponents] 已更新插件'设置面板 - "最近使用" 类别', 刷新后生效
[customNavbar.items.darkMode] 已更新插件'自定义顶栏 - 夜间模式开关', 刷新后生效
[keymap.actions.darkMode] 已更新插件'快捷键扩展 - 夜间模式', 刷新后生效
[downloadVideo.outputs.aria2] 已更新插件'下载视频 - aria2 输出支持', 刷新后生效
[downloadVideo.outputs.idm] 已更新插件'下载视频 - IDM 输出支持', 刷新后生效
[downloadVideo.outputs.mpv] 已更新插件'下载视频 - MPV 输出支持', 刷新后生效
Bilibili Evolved.user.js:189 暂无样式更新
Bilibili Evolved.user.js:189 [自动更新器] 完成更新检查
```

**Comment by DemoJameson** [comment]
+1
