### ISSUE TITLE
评论时表情框和推荐列表有冲突

### ISSUE THREAD

**Issue by 1135108813** [the1812/Bilibili-Evolved#2992]
### 对应功能

Commit: 332b4c325

### 问题描述

![image](https://user-images.githubusercontent.com/46586346/153338233-157f3015-8ed9-49f5-9d77-3e5deb7be245.png)
表情框和推荐列表冲突了。

![image](https://user-images.githubusercontent.com/46586346/153339198-bee09a3d-08f9-42c3-8498-f7dc7b93472f.png)

如果不开扩展，表情按钮在左侧，就不会有这个问题
![image](https://user-images.githubusercontent.com/46586346/153339345-2fda46b9-ad5b-46d9-a50d-c36317eea878.png)

### 脚本版本

v2.1.3-4-g332b4c325

### 浏览器版本

edge 97.0.1072.62

### 播放器版本

2.73.7-a306a712

### 错误信息

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at HTMLAnchorElement.eval (emoji.js:93:72)
    at HTMLDivElement.dispatch (jsc-player.88cefe51.js:41:2596)
    at HTMLDivElement.n (jsc-player.88cefe51.js:40:2602)
    at HTMLDivElement.sentryWrapped (sentry-5.7.1.min.js:2:37371)
eval @ emoji.js:93
dispatch @ jsc-player.88cefe51.js:41
n @ jsc-player.88cefe51.js:40
sentryWrapped @ sentry-5.7.1.min.js:2
```

**Comment by the1812** [comment]
返回旧版播放器
