### ISSUE TITLE
视频下载失败并跳转403

### ISSUE THREAD

**Issue by 189220122** [the1812/Bilibili-Evolved#3021]
### 对应功能

下载视频

### 问题描述

点击下载视频后页面跳转到403 Forbidden

### 脚本版本

v2.1.3-4-g332b4c325

### 浏览器版本

98.0.1108.55

### 错误信息

```shell
info: mode: default blocked_vip: undefined server: https://www.biliplus.com upos_server: undefined flv_prefer_ws:  remove_pre_ad: undefined generate_sub: undefined enable_in_av: undefined readyState: loading isLogin: false isLoginBiliBili: true
video.b801a9d9.js?v=20210111:176 
        
       The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
(匿名) @ video.b801a9d9.js?v=20210111:176
nc-loader-1.13.5.min.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:203701)
    at he.window (s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:223804)
    at Module.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:224572)
    at r (s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:146)
    at Object.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:86017)
    at r (s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:146)
    at s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:945
    at t (s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:955)
    at s1.hdslb.com/bfs/static/nc/nc-loader-1.13.5.min.js:2:227990
userscript.html?name=%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4.user.js&id=a6e51008-78cc-4c1f-ac18-bf194059ee09:128 
        
       Uncaught TypeError: list[i] is not a function
    at unhook (userscript.html?name=%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4.user.js&id=a6e51008-78c…:128:14)
    at unhook_t (userscript.html?name=%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4.user.js&id=a6e51008-78c…:120:12)
```

### 附加截图

![403](https://user-images.githubusercontent.com/49953092/154523339-5dd3f222-5cba-4129-a63b-dc3ffa74c859.png)

**Comment by kaixinol** [comment]
我也是这种情况，不过貌似刷新一下就正常了

**Comment by yeahjack** [comment]
> 我也是这种情况，不过貌似刷新一下就正常了

我刷新了还是403提示（
