### ISSUE TITLE
直播间简化的标题栏活动开启后主播头像没跟随缩小

### ISSUE THREAD

**Issue by KnightEmperor** [the1812/Bilibili-Evolved#3084]
### 对应功能

如题

### 问题描述

今天直播间简化的标题栏活动开启后主播头像没跟随缩小，之前一直好好的

### 脚本版本

v2.1.5-preview

### 浏览器版本

Edge 版本 98.0.1108.62

### 播放器版本

Bilibili HTML5 Live Player 3.6.28

### 错误信息

```shell
[TimeHooker] loading outer window...
userscript.html?name=%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8.user.js&id=2f6647bf-03b2-4bea-9236-652fa014888e:2358 Time Hooker Works!
userscript.html?name=%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4(%E6%94%B9).user.js&id=1a9c7b1b-fd72-48a5-99ea-ec4dcc6388bb:204 脚本: 复制限制解除(改) --- 开始执行 --- 发布者: qxin --- GitHub: https://github.com/qxinGitHub/Remove-web-limits-
room-player.min.js:29 fMp4Player v1.38
bilibili.b1b44d4ebbed329dfb16.js:2 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
bilibili.b1b44d4ebbed329dfb16.js:2 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
ocrad.min.js:5 
        
       Invalid asm.js: Unexpected token
crack.js:1 super_copy_cracked:false
vendors.bundle.js:1011  ____ _____ _      _____ ____ _____ _      _____ _    _ ______ _      _____  ______ _____|  _ |_   _| |    |_   _|  _ |_   _| |    |_   _| |  | |  ____| |    |  __ \|  ____|  __ \| |_) || | | |      | | | |_) || | | |      | | | |__| | |__  | |    | |__) | |__  | |__) ||  _ < | | | |      | | |  _ < | | | |      | | |  __  |  __| | |    |  ___/|  __| |  _  /| |_) _| |_| |____ _| |_| |_) _| |_| |____ _| |_| |  | | |____| |____| |    | |____| | \ \|____|_____|______|_____|____|_____|______|_____|_|  |_|______|______|_|    |______|_|  \_\-... .. .-.. .. -... .. .-.. ..    .... . .-.. .--. . .-.   version: 1.2.30 from: global
room-player.min.js:29 Chrome verion: 98
179.473f18d3bd1eb5ec0fcf.js:2 Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2022 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
179.473f18d3bd1eb5ec0fcf.js:2 Version: V4.0.0 "Life Experience", CodeName: Neptune.
content.js:1 BI <<<<<
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=4e1c179c-9cae-48ef-8869-515feaaf6f6a:194 live watch
userscript.html?name=%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8.user.js&id=2f6647bf-03b2-4bea-9236-652fa014888e:2878 [TimeHooker] loading inner window...
179.473f18d3bd1eb5ec0fcf.js:2 
        
       统计脚本加载失败： Error: Could not load URL at //s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js
    at HTMLScriptElement.i.onerror (bilibili.b1b44d4ebbed329dfb16.js:2:784317)
console.error @ 179.473f18d3bd1eb5ec0fcf.js:2
VM395:1 draw button =  null
21753989:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 400 ()
bilibili.b1b44d4ebbed329dfb16.js:2 
        
       Uncaught (in promise) Error: Could not load URL at //s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js
    at HTMLScriptElement.i.onerror (bilibili.b1b44d4ebbed329dfb16.js:2:784317)
undefined:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 ()
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=4e1c179c-9cae-48ef-8869-515feaaf6f6a:228 updated widgets Array(3)
vendors.bundle.js:2834 
        
       Not find container .room-info-down-row .attention-btn-ctnr
(匿名) @ vendors.bundle.js:2834
21753989:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 400 ()
7[Violation]'pointermove' handler 用时 <N> 毫秒
19[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
7[Violation]Added non-passive event listener to a scroll-blocking <某些> 事件. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
```

### 附加截图

![Snipaste_2022-03-04_11-34-24](https://user-images.githubusercontent.com/69032631/156696171-ac7f1af4-92cc-428a-8c15-94356ff336ae.png)

**Comment by the1812** [comment]
直播间有一小点改版
