### ISSUE TITLE
`BV 号转换` 在番剧页 bug

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#3123]
### 对应功能

BV 号转换
Commit: 03af3fac2
内部名称: bvidConvert

### 问题描述

`BV 号转换` 的两个复制链接按钮在番剧页复制出来的链接好像也是有问题的。
如：
- av 号：https://www.bilibili.com/bangumi/play/av********
- BV 号：https://www.bilibili.com/bangumi/play/BV********

还有一个 #860 相关 bug：
非大会员先进入需大会员才能看的剧集，不显示 av/BV 号；接着切换到不需大会员也能看的分集，仍不显示 av/BV 号。

### 脚本版本

v2.1.6-preview

### 浏览器版本

Chrome 99.0.4844.51（正式版本） （64 位）

### 播放器版本

3.6.2-5291d7f1

### 播放策略

AVC

### 错误信息

```shell
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 plugins block time: 5.1ms for 20 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 plugins resolve time: 18.2ms for 20 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:233 window._ is deprecated, please use window.lodash instead.
get @ userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:233
get @ VM3481:25
90 @ VM3521:1
i @ VM3521:1
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 components block time: 8.3ms for 25 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 components resolve time: 5680.9ms for 25 items
iris.min.js?v=:1 crash module error: Cannot read properties of null (reading 'stack')
iris.min.js?v=:1 crash module error: Cannot read properties of null (reading 'stack')
nc-loader-2.1.6.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at O (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:301013)
    at he.window (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:321116)
    at Module.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:321884)
    at n (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:146)
    at Object.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:120167)
    at n (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:146)
    at s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:945
    at t (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:955)
    at s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:325302
O @ nc-loader-2.1.6.min.js:2
he.window @ nc-loader-2.1.6.min.js:2
(anonymous) @ nc-loader-2.1.6.min.js:2
n @ nc-loader-2.1.6.min.js:2
(anonymous) @ nc-loader-2.1.6.min.js:2
n @ nc-loader-2.1.6.min.js:2
(anonymous) @ nc-loader-2.1.6.min.js:2
t @ nc-loader-2.1.6.min.js:2
(anonymous) @ nc-loader-2.1.6.min.js:2
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 plugins block time: 6.4ms for 20 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 plugins resolve time: 33.1ms for 20 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 components block time: 4.5ms for 14 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 components resolve time: 187ms for 14 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 init block time: 3.9ms for 6 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 init resolve time: 5985.3ms for 6 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 init block time: 1.8ms for 6 items
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7328bc8e-3919-4a37-b908-10b87055958f:198 init resolve time: 873.6ms for 6 items
```

**Comment by the1812** [comment]
我都忘了现在为啥是把网址中最后的 av / bv 替换为复制中的 id, 而不是直接用 `https://www.bilibili.com/video/<id>` 的方式?

**Comment by Geeyun-JY3** [comment]
啥……啥意思

**Comment by the1812** [comment]
就是番剧也应该是 `https://www.bilibili.com/video/<id>` 的形式, 然后我翻了下 v1 的代码, 也是直接这么处理的. 不知道现在为啥改成了 ``url.replace(/\/[^\/]+$/, `/${id}`)``, 难道以前那种形式出过什么别的 bug?
你也不记得的话我就统一换回 `https://www.bilibili.com/video/<id>` 了

**Comment by Geeyun-JY3** [comment]
不记得了，我只知道如果 `https://www.bilibili.com/video/<id>` 指向的是番剧，会跳转。
