### ISSUE TITLE
aria2的下载支持插件，并没有出现 rpc选项。

### ISSUE THREAD

**Issue by mr-pounds** [the1812/Bilibili-Evolved#3129]
### 对应功能

aria2的下载支持插件

### 问题描述

aria2的下载支持插件，并没有出现 rpc选项。

### 脚本版本

2.1.6

### 浏览器版本

99.0.4844.51

### 错误信息

```shell
plugins block time: 1.2ms for 8 items
userscript.html?name=Bilibili%20Evolved.user.js&id=c8e10814-017e-42db-ab97-1b244fb06700:198 plugins resolve time: 2.3ms for 8 items
userscript.html?name=Bilibili%20Evolved.user.js&id=c8e10814-017e-42db-ab97-1b244fb06700:198 components block time: 0.6ms for 8 items
userscript.html?name=Bilibili%20Evolved.user.js&id=c8e10814-017e-42db-ab97-1b244fb06700:198 components resolve time: 4.7ms for 8 items
userscript.html?name=Bilibili%20Evolved.user.js&id=c8e10814-017e-42db-ab97-1b244fb06700:198 init block time: 0.4ms for 6 items
userscript.html?name=Bilibili%20Evolved.user.js&id=c8e10814-017e-42db-ab97-1b244fb06700:198 init resolve time: 190.6ms for 6 items
nc-loader-2.1.6.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at O (nc-loader-2.1.6.min.js:2:301013)
    at he.window (nc-loader-2.1.6.min.js:2:321116)
    at Module.<anonymous> (nc-loader-2.1.6.min.js:2:321884)
    at n (nc-loader-2.1.6.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.1.6.min.js:2:120167)
    at n (nc-loader-2.1.6.min.js:2:146)
    at nc-loader-2.1.6.min.js:2:945
    at t (nc-loader-2.1.6.min.js:2:955)
    at nc-loader-2.1.6.min.js:2:325302
O @ nc-loader-2.1.6.min.js:2
he.window @ nc-loader-2.1.6.min.js:2
(anonymous) @ nc-loader-2.1.6.min.js:2
n @ nc-loader-2.1.6.min.js:2
(anonymous) @ nc-loader-2.1.6.min.js:2
n @ nc-loader-2.1.6.min.js:2
(anonymous) @ nc-loader-2.1.6.min.js:2
t @ nc-loader-2.1.6.min.js:2
(anonymous) @ nc-loader-2.1.6.min.js:2
```

### 附加截图

![千锋2022版React全家桶教程_react零基础入门到项目实战完整版_哔哩哔哩_bilibili](https://user-images.githubusercontent.com/30515791/158166511-45e6ec56-958d-4015-aa28-426d0e88debf.png)

**Comment by the1812** [comment]
往下滚动一点

**Comment by mr-pounds** [comment]
您好，我已经收到您的邮件。

**Comment by Pual397** [comment]
是开始这一行的ui元素遮住了，使用广告拦截选中这个元素，屏蔽掉就能选RPC了。然后再还原广告规则。
