### ISSUE TITLE
跳过充电鸣谢失效

### ISSUE THREAD

**Issue by KnightEmperor** [the1812/Bilibili-Evolved#3147]
### 对应功能

跳过充电鸣谢（Commit: 03af3fac2）

### 问题描述

大概率是播放器又改版了，最近跳过充电鸣谢无效

### 脚本版本

v2.1.6-preview

### 浏览器版本

版本 99.0.1150.46

### 播放器版本

3.6.7-b0c77af9

### 错误信息

```shell
____ _____ _      _____ ____ _____ _      _____ _    _ ______ _      _____  ______ _____|  _ |_   _| |    |_   _|  _ |_   _| |    |_   _| |  | |  ____| |    |  __ \|  ____|  __ \| |_) || | | |      | | | |_) || | | |      | | | |__| | |__  | |    | |__) | |__  | |__) ||  _ < | | | |      | | |  _ < | | | |      | | |  __  |  __| | |    |  ___/|  __| |  _  /| |_) _| |_| |____ _| |_| |_) _| |_| |____ _| |_| |  | | |____| |____| |    | |____| | \ \|____|_____|______|_____|____|_____|______|_____|_|  |_|______|______|_|    |______|_|  \_\-... .. .-.. .. -... .. .-.. ..    .... . .-.. .--. . .-.   version: 1.2.30 from: video
vendors.bundle.js:1011  ____ _____ _      _____ ____ _____ _      _____ _    _ ______ _      _____  ______ _____|  _ |_   _| |    |_   _|  _ |_   _| |    |_   _| |  | |  ____| |    |  __ \|  ____|  __ \| |_) || | | |      | | | |_) || | | |      | | | |__| | |__  | |    | |__) | |__  | |__) ||  _ < | | | |      | | |  _ < | | | |      | | |  __  |  __| | |    |  ___/|  __| |  _  /| |_) _| |_| |____ _| |_| |_) _| |_| |____ _| |_| |  | | |____| |____| |    | |____| | \ \|____|_____|______|_____|____|_____|______|_____|_|  |_|______|______|_|    |______|_|  \_\-... .. .-.. .. -... .. .-.. ..    .... . .-.. .--. . .-.   version: 1.2.30 from: global
VM688:4 
        
       Uncaught ReferenceError: __GetCookie is not defined
    at <anonymous>:4:42
    at <anonymous>:21:19
VM806 nc-loader-2.1.6.min.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at O (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:301013)
    at he.window (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:321116)
    at Module.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:321884)
    at n (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:146)
    at Object.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:120167)
    at n (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:146)
    at s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:945
    at t (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:955)
    at s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:325302
VM516:13 
        
       window._ is deprecated, please use window.lodash instead.
nt @ VM516:13
content.js:1 BI <<<<<
content.js:1 in settings
BV14u411q7SA:1 
        
       Mixed Content: The page at 'https://www.bilibili.com/video/BV14u411q7SA' was loaded over HTTPS, but requested an insecure element 'http://i1.hdslb.com/bfs/archive/e5e29711fc4ce8b3f8e87fd0ef365ea2e7227b96.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
VM129:13 [TimeHooker] loading inner window...
VM922:13 [TimeHooker] loading inner window...
nc-loader-2.1.6.min.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at O (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:301013)
    at he.window (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:321116)
    at Module.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:321884)
    at n (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:146)
    at Object.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:120167)
    at n (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:146)
    at s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:945
    at t (s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:955)
    at s1.hdslb.com/bfs/static/nc/nc-loader-2.1.6.min.js:2:325302
BV14u411q7SA:1 
        
       Mixed Content: The page at 'https://www.bilibili.com/video/BV14u411q7SA' was loaded over HTTPS, but requested an insecure element 'http://i1.hdslb.com/bfs/archive/e5e29711fc4ce8b3f8e87fd0ef365ea2e7227b96.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
BV14u411q7SA:1 
        
       Mixed Content: The page at 'https://www.bilibili.com/video/BV14u411q7SA' was loaded over HTTPS, but requested an insecure element 'http://i1.hdslb.com/bfs/archive/e5e29711fc4ce8b3f8e87fd0ef365ea2e7227b96.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
3VM516:13 requestedPopup true
BV14u411q7SA:1 
        
       Mixed Content: The page at 'https://www.bilibili.com/video/BV14u411q7SA' was loaded over HTTPS, but requested an insecure element 'http://i1.hdslb.com/bfs/archive/e5e29711fc4ce8b3f8e87fd0ef365ea2e7227b96.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
229.js:2 [Violation]'pointermove' handler took 336ms
[Violation]Forced reflow while executing JavaScript took 335ms
229.js:2 [Violation]'pointermove' handler took 352ms
[Violation]Forced reflow while executing JavaScript took 351ms
229.js:2 [Violation]'pointermove' handler took 392ms
[Violation]Forced reflow while executing JavaScript took 391ms
229.js:2 [Violation]'pointermove' handler took 282ms
[Violation]Forced reflow while executing JavaScript took 281ms
```

### 附加截图

![Snipaste_2022-03-20_07-30-46](https://user-images.githubusercontent.com/69032631/159142013-6bc04668-f8c4-49f2-aabe-dbd681569d3e.png)

**Comment by the1812** [comment]
右下角有没有返回旧版播放器

**Comment by KnightEmperor** [comment]
没有，一直用的是旧版。

**Comment by the1812** [comment]
我这边播放器版本还是 2.75.5-rc.3622.0-add04940

**Comment by KnightEmperor** [comment]
点开更新历史确实已经更到3.6.x了，但是我直接开无痕看确实还是2.75.0。不知道原因
![Snipaste_2022-03-20_11-38-53](https://user-images.githubusercontent.com/69032631/159147084-bb2320f8-69e1-422c-a333-da2e6dd5de6d.png)
![Snipaste_2022-03-20_11-37-54](https://user-images.githubusercontent.com/69032631/159147085-c13c8284-eed6-4499-be7f-cfbb99386d6c.png)
![Snipaste_2022-03-20_11-38-31](https://user-images.githubusercontent.com/69032631/159147086-831fa9fa-fac8-4abb-adfe-9b4f32118640.png)
。

**Comment by the1812** [comment]
合并至 #3187
