### ISSUE TITLE
记忆倍速 - 倍速还原操作失败 TypeError: (0 , b.des) is not a function

### ISSUE THREAD

**Issue by LYTPride** [the1812/Bilibili-Evolved#3169]
### 对应功能

记忆倍速rememberVideoSpeed；扩展倍速extendVideoSpeed

### 问题描述

倍速还原操作失败 TypeError: (0 , b.des) is not a function
通过倍速扩展功能添加1.75倍速，更新版本2.1.7后，下载倍速相关的组件和插件，仍然提示倍速还原操作失败，新建自定义倍速值1.75，倍速列表中显示自定义的1.75的值，实际播放也能切换到1.75这个速度，但是下方“倍速”按钮文字不变，展开列表1.75也不变色。刷新视频或者进入下一p就会报错，并且回到默认的1.0倍速。实测其他数值比如4.0，也是一样的。

### 脚本版本

v2.1.7

### 浏览器版本

Google Chrome 版本 99.0.4844.82（正式版本） （64 位）
Microsoft Edge 版本 99.0.1150.46 (正式版本) (64 位)

### 播放器版本

2.75.11

### 播放策略

默认

### 错误信息

```shell
倍速还原操作失败 TypeError: (0 , b.des) is not a function

Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at O (s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:310199)
    at he.window (s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:330302)
    at Module.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:331070)
    at n (s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:146)
    at Object.<anonymous> (s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:127079)
    at n (s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:146)
    at s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:945
    at t (s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:955)
    at s1.hdslb.com/bfs/static/nc/nc-loader-2.4.9.min.js:2:334488
VM1981:1 TypeError: (0 , b.des) is not a function
    at query (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved.user.js&id=85dc85b8-f90e-4a7d-a470-f602b9dc9b99), <anonymous>:1:4988)
    at a (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved.user.js&id=85dc85b8-f90e-4a7d-a470-f602b9dc9b99), <anonymous>:1:7207)
    at G.eval [as setVideoSpeed] (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved.user.js&id=85dc85b8-f90e-4a7d-a470-f602b9dc9b99), <anonymous>:1:10025)
    at async eval (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved.user.js&id=85dc85b8-f90e-4a7d-a470-f602b9dc9b99), <anonymous>:1:13106)
eval @ VM1981:1
3VM1988:2 Uncaught TypeError: (0 , m.dea) is not a function or its return value is not iterable
    at X.forceUpdateStyle (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved.user.js&id=85dc85b8-f90e-4a7d-a470-f602b9dc9b99), <anonymous>:2:2830)
    at Proxy.eval (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved.user.js&id=85dc85b8-f90e-4a7d-a470-f602b9dc9b99), <anonymous>:2:1981)
    at nt (<anonymous>:13:1036)
    at t.<computed> (eval at exec_fn (av93347594:3:113), <anonymous>:38:425)
    at nt (<anonymous>:13:1036)
    at a (eval at exec_fn (av93347594:3:113), <anonymous>:3:448)
    at eval (eval at exec_fn (av93347594:3:113), <anonymous>:4:111)
    at <anonymous>:6:142
    at x (<anonymous>:6:161)
2VM1948:28 requestedPopup true
activity-report.js:112 Uncaught ReferenceError: reportObserver is not defined
    at sendReporter (activity-report.js:112:5)
    at activity-report.js:189:3
    at activity-report.js:293:3
vendors.3b9cdc5c9000357ce991.js:7 Uncaught (in promise) Error: Could not load URL at //s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js
    at HTMLScriptElement.i.onerror (vendors.3b9cdc5c9000357ce991.js:7:87901)
```

### 附加截图

![snipaste_20220324_092334](https://user-images.githubusercontent.com/26462009/159823845-4fc46f2b-b692-4e80-abd9-8012f2766989.png)

**Comment by the1812** [comment]
#3163
