### ISSUE TITLE
直播信息扩充失效

### ISSUE THREAD

**Issue by ITsYYT** [the1812/Bilibili-Evolved#3200]
### 对应功能

功能：直播信息扩充
Commit：e5257ca7b
内部名称: extendFeedsLive

### 问题描述

在“动态首页”下的直播信息扩充失效，“正在直播”中只能显示最多10个直播间

### 脚本版本

v2.1.7

### 浏览器版本

Microsoft Edge 版本 99.0.1150.55 (正式版本) (64 位)

### 播放器版本

HTML5播放器 3.7.1

### 播放策略

默认

### 错误信息

```shell
Error handling response: Error: Blocked a frame with origin "https://s1.hdslb.com" from accessing a cross-origin frame.
    at tryShowingMateBar (eval at success (chrome-extension://kacbklkbjmnjkhnellgciecdogkkldoj/src/kernel/kernel.js:233:37), <anonymous>:5428:57)
    at eval (eval at success (chrome-extension://kacbklkbjmnjkhnellgciecdogkkldoj/src/kernel/kernel.js:233:37), <anonymous>:153:17)
    at eval (eval at success (chrome-extension://kacbklkbjmnjkhnellgciecdogkkldoj/src/kernel/kernel.js:233:37), <anonymous>:108:27)
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
Failed to load resource: the server responded with a status of 404 ()
Array(7)0: {__ob__: Ie}count: (...)href: (...)name: (...)prop: (...)__ob__: Ie {value: {…}, dep: fe, vmCount: 0}dep: fe {id: 1144, subs: Array(1)}value: {__ob__: Ie}vmCount: 0[[Prototype]]: Objectget count: ƒ ()set count: ƒ (t)get href: ƒ ()set href: ƒ (t)get name: ƒ ()set name: ƒ (t)get prop: ƒ ()set prop: ƒ (t)[[Prototype]]: Object1: {__ob__: Ie}count: (...)href: (...)name: (...)prop: (...)__ob__: Ie {value: {…}, dep: fe, vmCount: 0}get count: ƒ ()set count: ƒ (t)get href: ƒ ()set href: ƒ (t)get name: ƒ ()set name: ƒ (t)get prop: ƒ ()set prop: ƒ (t)[[Prototype]]: Object2: {__ob__: Ie}count: (...)href: (...)name: (...)prop: (...)__ob__: Ie {value: {…}, dep: fe, vmCount: 0}get count: ƒ ()set count: ƒ (t)get href: ƒ ()set href: ƒ (t)get name: ƒ ()set name: ƒ (t)get prop: ƒ ()set prop: ƒ (t)[[Prototype]]: Object3: {__ob__: Ie}4: {__ob__: Ie}5: {__ob__: Ie}6: {__ob__: Ie}count: (...)href: (...)name: (...)__ob__: Ie {value: {…}, dep: fe, vmCount: 0}get count: ƒ ()set count: ƒ (t)get href: ƒ ()set href: ƒ (t)get name: ƒ ()set name: ƒ (t)[[Prototype]]: Objectlength: 7[[Prototype]]: Array(0)
VM8:13 reply 0 0
VM8:13 at 0 0
VM8:13 like 0 0
VM8:13 sys_msg 0 8
VM8:13 user_msg 0 109
Error handling response: Error: Blocked a frame with origin "https://message.bilibili.com" from accessing a cross-origin frame.
    at tryShowingMateBar (eval at success (chrome-extension://kacbklkbjmnjkhnellgciecdogkkldoj/src/kernel/kernel.js:233:37), <anonymous>:5428:57)
    at eval (eval at success (chrome-extension://kacbklkbjmnjkhnellgciecdogkkldoj/src/kernel/kernel.js:233:37), <anonymous>:153:17)
    at eval (eval at success (chrome-extension://kacbklkbjmnjkhnellgciecdogkkldoj/src/kernel/kernel.js:233:37), <anonymous>:108:27)
Failed to load resource: the server responded with a status of 404 ()
VM8:13 
        
       feedsCardsManager.startWatching() failed
nt @ VM8:13
Failed to load resource: the server responded with a status of 404 ()
GET https://t.bilibili.com/undefined 404
```

### 附加截图

![123](https://user-images.githubusercontent.com/64056911/160826776-51795be7-7197-40e3-a8bc-f6cd56f0b546.png)

**Comment by Geeyun-JY3** [comment]
请看置顶，动态首页问题汇总至：#3191
