### ISSUE TITLE
多P视频夜间模式看不清分P的标题

### ISSUE THREAD

**Issue by DebuNeko233** [the1812/Bilibili-Evolved#3216]
### 对应功能

多P视频夜间模式看不清分P的标题

### 问题描述

https://www.bilibili.com/video/BV18J411W7cE?p=232&t=45.0

### 脚本版本

2.1.7

### 浏览器版本

edge 100.0.1185.29

### 播放器版本

2.76.5

### 播放策略

默认

### 错误信息

```shell
Array(7)
VM150:13 reply 0 0
VM150:13 at 0 0
VM150:13 like 0 1
VM150:13 sys_msg 0 0
VM150:13 user_msg 0 159
bili-header.umd.js:1 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
VM150:13 [URL params clean] https://www.bilibili.com/video/BV18J411W7cE?p=230&spm_id_from=pageDriver https://www.bilibili.com/video/BV18J411W7cE?p=230
2content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
2VM150:13 requestedPopup true
VM150:13 requestedPopup false
4content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
VM150:13 requestedPopup true
3content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
VM150:13 [URL params clean] https://www.bilibili.com/video/BV18J411W7cE?p=231&spm_id_from=pageDriver https://www.bilibili.com/video/BV18J411W7cE?p=231
34content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
VM150:13 requestedPopup true
7content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
VM150:13 [URL params clean] https://www.bilibili.com/video/BV18J411W7cE?p=232&spm_id_from=pageDriver https://www.bilibili.com/video/BV18J411W7cE?p=232
24content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
VM150:13 updated widgets Array(8)
content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
2VM150:13 requestedPopup false
5content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
3VM150:13 requestedPopup false
VM150:13 requestedPopup true
3VM150:13 requestedPopup false
VM150:13 requestedPopup true
5VM150:13 requestedPopup false
2content-script-start.js:2318 
        
       Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2318:18)
VM150:13 requestedPopup false
VM150:13 requestedPopup true
```

### 附加截图

![屏幕截图(15)](https://user-images.githubusercontent.com/101854723/161702580-1d1b62d5-76ab-4add-8427-deb9ad4fd59f.png)

**Comment by Geeyun-JY3** [comment]
新版界面没适配：#2615
