### ISSUE TITLE
登陆大会员账号后所有已安装组件功能全部无法使用，功能里全部不显示

### ISSUE THREAD

**Issue by shido520** [the1812/Bilibili-Evolved#3328]
### 对应功能

全部

### 问题描述

登陆大会员（购买了年费VIP）账号后所有已安装组件功能全部无法使用，功能里全部不显示。但如果用一个普通会员（无VIP权限）账号登陆，功能就正常。

### 脚本版本

v2.1.10-preview-1-g73fa9af28

### 浏览器版本

Chrome 101.0.4951.54 x64 和 Cent Browser (Chromium 86.0.4240.198)

### 播放器版本

3.8.14

### 播放策略

默认

### 错误信息

```shell
Bilibili Evolved 网址参数清理 https://www.bilibili.com/video/BV154411g7Nk?spm_id_from=333.880.my_history.page.click https://www.bilibili.com/video/BV154411g7Nk
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup true
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved Array(7)
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved reply 0 0
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved at 0 0
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved like 0 0
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved sys_msg 0 0
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved user_msg 0 23
/video/BV154411g7Nk:1 Mixed Content: The page at 'https://www.bilibili.com/video/BV154411g7Nk' was loaded over HTTPS, but requested an insecure element 'http://i1.hdslb.com/bfs/archive/a8a816fb615e2651b6faeb69a5b0da638297bc36.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/video/BV154411g7Nk:1 Mixed Content: The page at 'https://www.bilibili.com/video/BV154411g7Nk' was loaded over HTTPS, but requested an insecure element 'http://i1.hdslb.com/bfs/archive/a8a816fb615e2651b6faeb69a5b0da638297bc36.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
VM386 nc-loader-2.6.4.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.4.min.js:2:353483)
    at he.window (nc-loader-2.6.4.min.js:2:373587)
    at Module.<anonymous> (nc-loader-2.6.4.min.js:2:374355)
    at r (nc-loader-2.6.4.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.4.min.js:2:130873)
    at r (nc-loader-2.6.4.min.js:2:146)
    at nc-loader-2.6.4.min.js:2:945
    at t (nc-loader-2.6.4.min.js:2:955)
    at nc-loader-2.6.4.min.js:2:377773
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup true
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup false
bilibili.js:2 bilibili.js
bilibili.js:28 insert fbion div
​ bilibili.js
​ insert fbion div
​ error https://www.bilibili.com/video/BV154411g7Nk
​ bilibili.js
​ insert fbion div
bilibili.js:2 bilibili.js
​ bilibili.js
​ error https://www.bilibili.com/video/BV154411g7Nk
​ bilibili.js
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved updated widgets Array(1)
VM521 nc-loader-2.6.4.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.4.min.js:2:353483)
    at he.window (nc-loader-2.6.4.min.js:2:373587)
    at Module.<anonymous> (nc-loader-2.6.4.min.js:2:374355)
    at r (nc-loader-2.6.4.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.4.min.js:2:130873)
    at r (nc-loader-2.6.4.min.js:2:146)
    at nc-loader-2.6.4.min.js:2:945
    at t (nc-loader-2.6.4.min.js:2:955)
    at nc-loader-2.6.4.min.js:2:377773
VM522 nc-loader-2.6.4.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.4.min.js:2:353483)
    at he.window (nc-loader-2.6.4.min.js:2:373587)
    at Module.<anonymous> (nc-loader-2.6.4.min.js:2:374355)
    at r (nc-loader-2.6.4.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.4.min.js:2:130873)
    at r (nc-loader-2.6.4.min.js:2:146)
    at nc-loader-2.6.4.min.js:2:945
    at t (nc-loader-2.6.4.min.js:2:955)
    at nc-loader-2.6.4.min.js:2:377773
VM523 nc-loader-2.6.4.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.4.min.js:2:353483)
    at he.window (nc-loader-2.6.4.min.js:2:373587)
    at Module.<anonymous> (nc-loader-2.6.4.min.js:2:374355)
    at r (nc-loader-2.6.4.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.4.min.js:2:130873)
    at r (nc-loader-2.6.4.min.js:2:146)
    at nc-loader-2.6.4.min.js:2:945
    at t (nc-loader-2.6.4.min.js:2:955)
    at nc-loader-2.6.4.min.js:2:377773
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup true
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup false
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup true
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup false
3userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup true
activity-report.js:112 Uncaught ReferenceError: reportObserver is not defined
    at sendReporter (activity-report.js:112:5)
    at activity-report.js:189:3
    at activity-report.js:293:3
vendors.3b9cdc5c9000357ce991.js:7 Uncaught (in promise) Error: Could not load URL at //s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js
    at HTMLScriptElement.i.onerror (vendors.3b9cdc5c9000357ce991.js:7:87901)
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup false
nc-loader-2.6.4.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.4.min.js:2:353483)
    at he.window (nc-loader-2.6.4.min.js:2:373587)
    at Module.<anonymous> (nc-loader-2.6.4.min.js:2:374355)
    at r (nc-loader-2.6.4.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.4.min.js:2:130873)
    at r (nc-loader-2.6.4.min.js:2:146)
    at nc-loader-2.6.4.min.js:2:945
    at t (nc-loader-2.6.4.min.js:2:955)
    at nc-loader-2.6.4.min.js:2:377773
npd.community-helper.fce2c60f.js:72 Timer 'worker' already exists
worker.onmessage @ npd.community-helper.fce2c60f.js:72
BV154411g7Nk:1 Mixed Content: The page at 'https://www.bilibili.com/video/BV154411g7Nk?p=2' was loaded over HTTPS, but requested an insecure element 'http://i1.hdslb.com/bfs/archive/a8a816fb615e2651b6faeb69a5b0da638297bc36.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
BV154411g7Nk:1 Mixed Content: The page at 'https://www.bilibili.com/video/BV154411g7Nk?p=2' was loaded over HTTPS, but requested an insecure element 'http://i1.hdslb.com/bfs/archive/a8a816fb615e2651b6faeb69a5b0da638297bc36.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
2userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup false
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=60ae27b6-889e-4c73-a575-e141b8947b69:219 Bilibili Evolved requestedPopup true
```

### 附加截图

![222](https://user-images.githubusercontent.com/29383072/168430081-f583515d-5f66-4640-8d50-7707fa5b8c7a.png)
![333](https://user-images.githubusercontent.com/29383072/168430087-b228404b-b325-4c4f-91ab-f36ef96a00ce.png)

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/168430177-7ab3c9eb-c1ee-4456-98f0-9087651166d9.png)
