### ISSUE TITLE
快速收藏模块时效

### ISSUE THREAD

**Issue by visiLi** [the1812/Bilibili-Evolved#3346]
### 对应功能

模块版本：
Commit: 73fa9af28
内部名称: quickFavorite

### 问题描述

快速收藏模块不显示了
如图：
<img src="https://z4a.net/images/2022/05/22/_20220522132815.png" alt="_20220522132815.png" border="0" />

### 脚本版本

Bilibili Evolved (Preview) v2.1.10-preview-1-g73fa9af28 

### 浏览器版本

Edge 100.0.1185.29

### 播放器版本

V3.9.2

### 播放策略

AVC

### 错误信息

```shell
content-script-start.js:2582 Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2582:18)
content-script-start.js:2582 Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2582:18)
content-script-start.js:2582 Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2582:18)
content-script-start.js:2582 Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2582:18)
content-script-start.js:2582 Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2582:18)
```

**Comment by visiLi** [comment]
在火狐浏览器也是失效的。

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/169690632-75864a27-c25e-47b8-8f96-81e9e4aa7125.png)
