### ISSUE TITLE
开启网址AV号转换后，点击右侧推荐视频后网址av号不变

### ISSUE THREAD

**Issue by yuban01652** [the1812/Bilibili-Evolved#3402]
### 对应功能

网址AV号转换
Commit: 70a2709ba

### 问题描述

启动网页av号转换插件，后打开一个视频，如av806609197
点击该视频右侧的推荐视频，如BV18L411J7Br，视频跳转后网址仍保持av806609197，点击刷新按钮会回退到上一个视频av806609197
点击推荐视频后，点击后退按钮，前进按钮，网址均为上一个视频av806609197
关闭网页av号转换插件后再点击推荐视频BV18L411J7Br，网址正确显示。

### 脚本版本

2.2.1

### 浏览器版本

102.0.5005.63（正式版本） （64 位）

### 播放器版本

2.78.5-04bf8055

### 播放策略

AV1

### 错误信息

```shell
Bilibili Evolved context update
m	@	userscript.html?name…d9-2799e63423c3:219
eval	@	VM20700:1
Promise.catch（异步）		
eval	@	VM20700:1
eval	@	VM20700:1
u	@	VM20700:1
next	@	VM20700:1
eval	@	VM20700:1
u	@	VM20700:1
eval	@	VM20700:1
Promise.then（异步）		
eval	@	VM20700:1
eval	@	VM20700:1
u	@	VM20700:1
eval	@	VM20700:1
eval	@	VM20700:1
u	@	VM20700:1
（匿名）	@	userscript.html?name…d9-2799e63423c3:196
it	@	VM20668:14
D.<computed>.I.<computed>	@	VM20668:4
（匿名）	@	userscript.html?name…d9-2799e63423c3:196
（匿名）	@	userscript.html?name…d9-2799e63423c3:196
nc-loader-2.6.7.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.7.min.js:2:355865)
    at he.window (nc-loader-2.6.7.min.js:2:375969)
    at Module.<anonymous> (nc-loader-2.6.7.min.js:2:376737)
    at r (nc-loader-2.6.7.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.7.min.js:2:130633)
    at r (nc-loader-2.6.7.min.js:2:146)
    at nc-loader-2.6.7.min.js:2:945
    at t (nc-loader-2.6.7.min.js:2:955)
    at nc-loader-2.6.7.min.js:2:380155
I	@	nc-loader-2.6.7.min.js:2
he.window	@	nc-loader-2.6.7.min.js:2
（匿名）	@	nc-loader-2.6.7.min.js:2
r	@	nc-loader-2.6.7.min.js:2
（匿名）	@	nc-loader-2.6.7.min.js:2
r	@	nc-loader-2.6.7.min.js:2
（匿名）	@	nc-loader-2.6.7.min.js:2
t	@	nc-loader-2.6.7.min.js:2
（匿名）	@	nc-loader-2.6.7.min.js:2
```

### 附加截图

![捕获1](https://user-images.githubusercontent.com/38140455/172025150-bc385ef7-e0ef-418a-962c-e6ee26c55d52.PNG)
![捕获2](https://user-images.githubusercontent.com/38140455/172025153-fa6ebed8-d7a8-4065-9fef-914124db33b1.PNG)

**Comment by the1812** [comment]
现在会变了, 不过这个功能仍然存在一些副作用
![image](https://user-images.githubusercontent.com/26504152/184772177-91d203c6-5671-464b-9607-a298464ba7cd.png)
