### ISSUE TITLE
[反馈] HEVC播放策略下关灯相关功能故障

### ISSUE THREAD

**Issue by ZippyRhys** [the1812/Bilibili-Evolved#3403]
### 对应功能

* 播放时自动关灯 `Commit: 24744b203`
* 播放器位置动作 `Commit: 24744b203`

### 问题描述

在HEVC播放策略下，出现下列问题：
* `播放器自动关灯`功能中，暂停后不自动开灯
* `播放器位置动作`功能中，页面往下滚动指定位置后不自动开灯
*  `播放器自动关灯`功能中，播放开始后自动关灯动作有延迟，相较其他播放策略(测试以avc为例)通常有数秒(不知这是否算bug)
* 测试过的视频中均出现了上述问题

### 脚本版本

v2.2.1-preview

### 浏览器版本

Microsoft Edge 版本 102.0.1245.33 (正式版本) (64 位)

### 播放器版本

2.78.5-04bf8055

### 播放策略

HEVC

### 错误信息

```shell
userscript.html?name=%25E5%2593%2594%25E5%2593%25A9%25E5%2593%2594%25E5%2593%25A9%25E7%2595%25AA%25E5%2589%25A7%25E8%25A7%25A3%25E9%2594%2581%25E5%25A4%25A7%25E4%25BC%259A%25E5%2591%2598%252CB%25E7%25AB%2599%25E8%25A7%2586%25E9%25A2%2591%25E4%25B8%258B%25E8%25BD%25BD%25E3%2580%2581%25E8%25A7%25A3%25E6%259E%2590%25EF%25BC%258CA%25E7%25AB%2599%25E8%25A7%2586%25E9%25A2%2591%25E4%25B8%258B%25E8%25BD%25BD%25E3%2580%2581%25E8%25A7%25A3%25E6%259E%2590%25EF%25BC%258C%25E9%259B%2586%25E5%2590%2588%25E4%25BA%2586%25E4%25BC%2598%25E9%2585%25B7%25E3%2580%2581%25E7%2588%25B1%25E5%25A5%2587%25E8%2589%25BA%25E3%2580%2581%25E8%2585%25BE%25E8%25AE%25AF%25E3%2580%2581%25E8%258A%2592%25E6%259E%259C%25E3%2580%2581%25E4%25B9%2590%25E8%25A7%2586%25E3%2580%2581%25E7%25AD%2589%25E5%2585%25A8%25E7%25BD%2591VIP%25E8%25A7%2586%25E9%25A2%2591%25E5%2585%258D%25E8%25B4%25B9%25E7%25A0%25B4%25E8%25A7%25A3%25E5%258E%25BB%25E5%25B9%25BF%25E5%2591%258A%252C%25E9%25AB%2598%25E6%25B8%2585%25E6%2599%25AE%25E6%25B8%2585%25E7%2594%25B5%25E8%25A7%2586%25E8%25A7%2582%25E7%259C%258B%25EF%25BC%258C%25E5%25A2%259E%25E5%258A%25A0%25E5%25AF%25B9%25E6%2589%258B%25E6%259C%25BA%25E6%2594%25AF%25E6%258C%2581%25EF%25BC%258C%25E6%258C%2581%25E7%25BB%25AD%25E6%259B%25B4%25E6%2596%25B0.user.js&id=2d0a674e-5360-423a-be97-4e272b8fde71:947 
        
       Uncaught SyntaxError: Unexpected end of input (at userscript.html?name=%25E5%2593%2594%25E5%2593%25A9%25E5%2593%2594%25E5%2593%25A9%25E7%2595%25AA%25E5%2589%25A7%25E8%25A7%25A3%25E9%2594%2581%25E5%25A4%25A7%25E4%25BC%259A%25E5%2591%2598%252CB%25E7%25AB%2599%25E8%25A7%2586%25E9%25A2%2591%25E4%25B8%258B%25E8%25BD%25BD%25E3%2580%2581%25E8%25A7%25A3%25E6%259E%2590%25EF%25BC%258CA%25E7%25AB%2599%25E8%25A7%2586%25E9%25A2%2591%25E4%25B8%258B%25E8%25BD%25BD%25E3%2580%2581%25E8%25A7%25A3%25E6%259E%2590%25EF%25BC%258C%25E9%259B%2586%25E5%2590%2588%25E4%25BA%2586%25E4%25BC%2598%25E9%2585%25B7%25E3%2580%2581%25E7%2588%25B1%25E5%25A5%2587%25E8%2589%25BA%25E3%2580%2581%25E8%2585%25BE%25E8%25AE%25AF%25E3%2580%2581%25E8%258A%2592%25E6%259E%259C%25E3%2580%2581%25E4%25B9%2590%25E8%25A7%2586%25E3%2580%2581%25E7%25AD%2589%25E5%2585%25A8%25E7%25BD%2591VIP%25E8%25A7%2586%25E9%25A2%2591%25E5%2585%258D%25E8%25B4%25B9%25E7%25A0%25B4%25E8%25A7%25A3%25E5%258E%25BB%25E5%25B9%25BF%25E5%2591%258A%252C%25E9%25AB%2598%25E6%25B8%2585%25E6%2599%25AE%25E6%25B8%2585%25E7%2594%25B5%25E8%25A7%2586%25E8%25A7%2582%25E7%259C%258B%25EF%25BC%258C%25E5%25A2%259E%25E5%258A%25A0%25E5%25AF%25B9%25E6%2589%258B%25E6%259C%25BA%25E6%2594%25AF%25E6%258C%2581%25EF%25BC%258C%25E6%258C%2581%25E7%25BB%25AD%25E6%259B%25B4%25E6%2596%25B0.user.js&id=2d0a674e-5360-423a-be97-4e272b8fde71:947:3)
    at it (<anonymous>:14:1074)
    at D.<computed>.I.<computed> (<anonymous>:4:485)
    at it (<anonymous>:14:1074)
    at y (<anonymous>:6:39)
    at Object.send (<anonymous>:7:128)
    at V (<anonymous>:3:307)
    at <anonymous>:4:275
    at E_u (<anonymous>:4:330)
    at <anonymous>:64:44
    at Object.create (<anonymous>:65:178)
it @ VM9274:14
D.<computed>.I.<computed> @ VM9274:4
it @ VM9274:14
y @ VM9274:6
send @ VM9274:7
V @ VM9274:3
(匿名) @ VM9274:4
E_u @ VM9274:4
(匿名) @ VM9275:64
create @ VM9275:65
l @ VM9275:6
it @ VM9274:14
a @ VM9275:3
(匿名) @ VM9275:4
(匿名) @ VM9274:6
M @ VM9274:6
setTimeout(异步)
setTimeout @ content.js:121
processMessage @ content.js:124
(匿名) @ content.js:128
(匿名) @ content.js:108
it @ VM9274:14
D.<computed>.I.<computed> @ VM9274:4
it @ VM9274:14
y @ VM9274:6
send @ VM9274:7
r @ VM9275:4
setTimeout @ VM9275:4
(匿名) @ VM9275:7
runListeners @ VM9275:6
(匿名) @ VM9275:66
M @ VM9274:6
s @ content.js:107
send @ content.js:108
(匿名) @ content.js:132
s @ content.js:106
window.addEventListener.capture @ content.js:111
stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Base')
    at stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153:563779
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
Promise.then(异步)
n @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
s @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
initAd @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
mounted @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
Wt @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
nn @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
insert @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
O @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
t._update @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
i @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
vn.get @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
vn @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
Sn.$mount @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
Sn.$mount @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
su.onReady @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
bu.onReady @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
n @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
n @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1
stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Base')
    at stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153:563779
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
Promise.then(异步)
n @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
s @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
initAd @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
mounted @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
Wt @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
nn @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
insert @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
O @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
t._update @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
i @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
vn.get @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
vn @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
Sn.$mount @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
Sn.$mount @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:7
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
su.onReady @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
bu.onReady @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
n @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:153
n @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1
(匿名) @ stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1
nc-loader-2.6.7.min.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.7.min.js:2:355865)
    at he.window (nc-loader-2.6.7.min.js:2:375969)
    at Module.<anonymous> (nc-loader-2.6.7.min.js:2:376737)
    at r (nc-loader-2.6.7.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.7.min.js:2:130633)
    at r (nc-loader-2.6.7.min.js:2:146)
    at nc-loader-2.6.7.min.js:2:945
    at t (nc-loader-2.6.7.min.js:2:955)
    at nc-loader-2.6.7.min.js:2:380155
I @ nc-loader-2.6.7.min.js:2
he.window @ nc-loader-2.6.7.min.js:2
(匿名) @ nc-loader-2.6.7.min.js:2
r @ nc-loader-2.6.7.min.js:2
(匿名) @ nc-loader-2.6.7.min.js:2
r @ nc-loader-2.6.7.min.js:2
(匿名) @ nc-loader-2.6.7.min.js:2
t @ nc-loader-2.6.7.min.js:2
(匿名) @ nc-loader-2.6.7.min.js:2
bliveproxy.min.js:179 
        
       Uncaught RangeError: Invalid typed array length: 167902685
    at new Uint8Array (<anonymous>)
    at handleMessage (bliveproxy.min.js:179:28)
    at myOnMessage (bliveproxy.min.js:90:9)
    at WebSocket.value (bliveproxy.min.js:72:21)
handleMessage @ bliveproxy.min.js:179
myOnMessage @ bliveproxy.min.js:90
value @ bliveproxy.min.js:72
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=2ee4516c-3c49-463a-bcfc-04e417540561:219 
        
       Bilibili Evolved Error: video element not found!
    at T (eval at loadFeatureCode (av512030280:196:65539), <anonymous>:1:5147)
m @ userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=2ee4516c-3c49-463a-bcfc-04e417540561:219
eval @ VM9298:1
VM9320:1 
        
       Uncaught TypeError: Cannot read properties of null (reading 'paused')
    at IntersectionObserver.eval (eval at loadFeatureCode (av512030280:196:65539), <anonymous>:1:1452)
eval @ VM9320:1
VM9320:1 
        
       Uncaught TypeError: Cannot read properties of null (reading 'paused')
    at IntersectionObserver.eval (eval at loadFeatureCode (av512030280:196:65539), <anonymous>:1:1452)
eval @ VM9320:1
```

### 附加截图

![屏幕截图 2022-06-05 115542](https://user-images.githubusercontent.com/34595052/172034396-03add7a0-e483-47dd-b2c7-f28e2848dde7.png)
![屏幕截图 2022-06-05 115606](https://user-images.githubusercontent.com/34595052/172034401-d3722986-0c0a-4e1f-8429-705af2b23cc7.png)
![屏幕截图 2022-06-05 123244](https://user-images.githubusercontent.com/34595052/172035143-f4a3b00e-d7fb-4ef8-958a-53d33b6287cc.png)

**Comment by ZippyRhys** [comment]
其实默认播放器模式也有Edge上失效但火狐可用的问题，不过因为看到说这个功能不维护了所以就没在上面提了...

**Comment by ZippyRhys** [comment]
另外`默认播放器模式`在HEVC下也失效了，不过看到说这个功能不维护了就放在issue里面了...
