### ISSUE TITLE
设置页图标丢失

### ISSUE THREAD

**Issue by xslongtui** [the1812/Bilibili-Evolved#3405]
### 对应功能

设置页

### 问题描述

点开设置页没有图标

### 脚本版本

v2.2.1

### 浏览器版本

Microsoft Edge 102.0.1245.33

### 播放器版本

2.78.5

### 播放策略

默认

### 错误信息

```shell
materialdesignicons.min.css:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_CONNECTION_RESET
materialdesignicons.min.css:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_CONNECTION_RESET
materialdesignicons.min.css:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_CONNECTION_RESET
www.bilibili.com/:1 
        
       Mixed Content: The page at 'https://www.bilibili.com/' was loaded over HTTPS, but requested an insecure element 'http://impression.biligame.com/api/impression/bilibili_pc?account_id=398908&campaign_id=1982509&unit_id=6154774&creative_id=96929016&supply_callback=pbaes.VQ_tjo2Z-MOJbaP7asGf8CwjLTrpZkcovpis1JOk9ztY6qckKryyPR6TWKGKvUAjKwP7iE5EnBVJw6xVPmHQvYRSARnQbagvmy3NS5efWCNnZbcsbEaWdxejQ0SXr3Wcup71KpD33WCEBtTHwz0pTnlVLgEwcTbzSe-2Rq_xbOw&callback_url=https%3a%2f%2fcm.bilibili.com%2fconv%2fapi%2fconversion%2fad%2fcb%2fv1%3ftrack_id%3dpbaes.VQ_tjo2Z-MOJbaP7asGf8CwjLTrpZkcovpis1JOk9ztY6qckKryyPR6TWKGKvUAjKwP7iE5EnBVJw6xVPmHQvYRSARnQbagvmy3NS5efWCNnZbcsbEaWdxejQ0SXr3Wcup71KpD33WCEBtTHwz0pTnlVLgEwcTbzSe-2Rq_xbOw&mid=475623045&os=3&idfa=__IDFA__&buvid=82229DBD-BC35-313F-661E-CB4D2927E35C35330infoc&android_id=__ANDROIDID__&oaid=__OAID__&imei=__IMEI__&mac=__MAC__&duid=__DUID__&ip=113.249.173.4&request_id=1654450511061q172a27a6a243q7053&ts=__TS__&ua=__UA__&ad_channel_id=3&ad_f=bc171e5edd184177a7ab9b8a866b76ef&game_id=4466'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
Bilibili Evolved.user.js:218 Bilibili Evolved Array(7)
Bilibili Evolved.user.js:218 Bilibili Evolved reply 0 0
Bilibili Evolved.user.js:218 Bilibili Evolved at 0 0
Bilibili Evolved.user.js:218 Bilibili Evolved like 0 0
Bilibili Evolved.user.js:218 Bilibili Evolved sys_msg 0 0
Bilibili Evolved.user.js:218 Bilibili Evolved user_msg 0 3
Bilibili Evolved.user.js:218 Bilibili Evolved updated widgets Array(3)
international-home.7e512478681091d5bdc2ddd9dba500dce586da48.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'forceCommit')
    at HTMLDocument.<anonymous> (international-home.7e512478681091d5bdc2ddd9dba500dce586da48.js:1:585982)
(匿名) @ international-home.7e512478681091d5bdc2ddd9dba500dce586da48.js:1
Bilibili Evolved.user.js:218 Bilibili Evolved requestedPopup true
international-home.7e512478681091d5bdc2ddd9dba500dce586da48.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'forceCommit')
    at HTMLDocument.<anonymous> (international-home.7e512478681091d5bdc2ddd9dba500dce586da48.js:1:585982)
(匿名) @ international-home.7e512478681091d5bdc2ddd9dba500dce586da48.js:1
```

### 附加截图

![image](https://user-images.githubusercontent.com/104275499/172063098-733ba7bc-1dc0-4830-b99f-2be782700e78.png)
![image](https://user-images.githubusercontent.com/104275499/172063140-2a7300ac-486d-4a71-93d7-2d76dd479fe4.png)
![image](https://user-images.githubusercontent.com/104275499/172063075-196d1e6d-40fe-4e3f-a98a-ca491ec22a46.png)
![image](https://user-images.githubusercontent.com/104275499/172063122-a1b45280-f63d-4a41-a9bc-2bb7f6aa5713.png)

**Comment by the1812** [comment]
梯子挂了没, 图标库的地址是 https://cdn.jsdelivr.net/gh/Templarian/MaterialDesign-Webfont@5.3.45/css/materialdesignicons.min.css
错误信息里显示加载超时了

**Comment by xslongtui** [comment]
哦哦，谢谢

**Comment by xslongtui** [comment]
（要不弄个本地……？

**Comment by xslongtui** [comment]
jsdelivr被墙了啊原来是
