### ISSUE TITLE
最新版本设置栏好多设置项消失了

### ISSUE THREAD

**Issue by Fpywyh** [the1812/Bilibili-Evolved#3423]
### 对应功能

设置栏显示异常

### 问题描述

前几天更新到最新版之后(v2.2.1)，以前版本的设置页有的许多设置项都不见了，但是以前的设置仍然能起作用，就是设置项消失之后就不能自定义重新更改设置了。

### 脚本版本

v2.2.1

### 浏览器版本

Chrome 102.0.5005.63（正式版本） （64 位）

### 播放器版本

网页版右键看不了版本号

### 播放策略

默认

### 错误信息

```shell
content-gm.js:1 createScriptData Object
2sentry-5.7.1.min.js:2 isShow false
nc-loader-2.6.8.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.8.min.js:2:355865)
    at he.window (nc-loader-2.6.8.min.js:2:375969)
    at Module.<anonymous> (nc-loader-2.6.8.min.js:2:376737)
    at r (nc-loader-2.6.8.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.8.min.js:2:130633)
    at r (nc-loader-2.6.8.min.js:2:146)
    at nc-loader-2.6.8.min.js:2:945
    at t (nc-loader-2.6.8.min.js:2:955)
    at nc-loader-2.6.8.min.js:2:380155
2userscript.html?name=Bilibili%2520Evolved.user.js&id=bb3d4a02-35d8-4998-9e8a-1e1a7c5a76f2:219 Bilibili Evolved requestedPopup true
```

### 附加截图

![反馈](https://user-images.githubusercontent.com/84830072/172876996-598b7b80-a75b-4a59-aaaf-1fe74b78ca55.JPG)

**Comment by imshixin** [comment]
是不是开了两个

**Comment by Fpywyh** [comment]
> 是不是开了两个

两个B站的相关插件吗？这个没有啊。什么也没变，就是Bilibili-Evolved更新之后就变成这样了。

**Comment by imshixin** [comment]
我是指两个bilibili evolved

**Comment by Fpywyh** [comment]
> 我是指两个bilibili evolved

没有啊，我截图你看看。如果这样不行的话能不能问一下怎么查看自己是否安装了两个呢？

![反馈](https://user-images.githubusercontent.com/84830072/173168490-d7b5f065-061b-4039-a448-850abfd0699a.JPG)

**Comment by Geeyun-JY3** [comment]
可以复现，还是 #3331 的问题，挂梯子就好了。
