### ISSUE TITLE
首页稍后再看无法点击

### ISSUE THREAD

**Issue by q56535** [the1812/Bilibili-Evolved#3882]
### 对应功能

未知

### 问题描述

首页的稍后再看无法点击，进视频页面的视频推荐可以点击稍后再看，不确定是否为脚本问题，因为此报错没有几乎没有出现`
Bilibili Evolved`相关

### 脚本版本

2.5.2-17-g89d37a1f2

### 浏览器版本

108.0.5359.125（正式版本） （64 位）

### 播放器版本

3.25.2-b425d8f7

### 播放策略

AV1

### 错误信息

```shell
TypeError: Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.
    at sentry-5.15.0.min.js:2:19494
    at Proxy.<anonymous> (index.2eba9e70.js:25:1868)
    at Generator.next (<anonymous>)
    at index.2eba9e70.js:1:708
    at new Promise (<anonymous>)
    at j (index.2eba9e70.js:1:528)
    at Proxy.doWatch (index.2eba9e70.js:25:1747)
    at Proxy.<anonymous> (index.2eba9e70.js:25:2042)
    at Generator.next (<anonymous>)
    at index.2eba9e70.js:1:708
    at new Promise (<anonymous>)
    at j (index.2eba9e70.js:1:528)
    at Proxy.addWatchLater (index.2eba9e70.js:25:1999)
    at Proxy.<anonymous> (index.2eba9e70.js:25:3193)
    at Generator.next (<anonymous>)
    at index.2eba9e70.js:1:708
    at new Promise (<anonymous>)
    at j (index.2eba9e70.js:1:528)
    at Proxy.watchHandle (index.2eba9e70.js:25:3088)
    at index.2eba9e70.js:25:3663
    at vendor.5582e141.js:4:77884
    at callWithErrorHandling (vendor.5582e141.js:4:866)
    at callWithAsyncErrorHandling (vendor.5582e141.js:4:1002)
    at HTMLDivElement.le (vendor.5582e141.js:4:71841)
    at HTMLDivElement.sentryWrapped (sentry-5.15.0.min.js:2:53430)
(anonymous) @ sentry-5.15.0.min.js:2
(anonymous) @ index.2eba9e70.js:25
s @ index.2eba9e70.js:1
Promise.then (async)
r @ index.2eba9e70.js:1
(anonymous) @ index.2eba9e70.js:1
j @ index.2eba9e70.js:1
watchHandle @ index.2eba9e70.js:25
(anonymous) @ index.2eba9e70.js:25
(anonymous) @ vendor.5582e141.js:4
callWithErrorHandling @ vendor.5582e141.js:4
callWithAsyncErrorHandling @ vendor.5582e141.js:4
le @ vendor.5582e141.js:4
sentryWrapped @ sentry-5.15.0.min.js:2
```

### 附加截图

![1 848_POS~CBZT7B26U3QJQ](https://user-images.githubusercontent.com/26663837/208287299-78989b24-f29e-4185-b967-61cb856990c8.png)
![80SDT8Y_W%F% A7D4%R7DAS](https://user-images.githubusercontent.com/26663837/208287311-64b34177-60e5-4c2b-95fa-516a5f1ca974.png)

**Comment by q56535** [comment]
初步证明与脚本无关，故暂时关闭
