### ISSUE TITLE
Mac更新后脚本无法启用

### ISSUE THREAD

**Issue by RexJiangEvoBio** [the1812/Bilibili-Evolved#4982]
### 对应功能

所有功能

### 问题描述

最近Mac系统更新到Sequoia后，Bilibili-Evolved无法启用。查看userscript manager限时脚本已启用，但进入屏幕左侧并未出现功能面板与设置面板入口。已重装脚本，但状况未有改变。

### 脚本版本

2.9.4

### 脚本管理器及版本

Tampermonkey v5.3.1

### 浏览器及版本

Google Chrome Version 130.0.6723.70 (Official Build) (arm64)

### 播放器版本

HTML5播放器 v4.8.47

### 播放策略

默认

### 错误信息

```Shell
Uncaught Error: Extension context invalidated.
    at c (content-script.js:1:1527)
    at u (content-script.js:1:95122)
    at content-script.js:1:95492
c @ content-script.js:1
u @ content-script.js:1
(anonymous) @ content-script.js:1
Show 3 more frames
Show lessUnderstand this errorAI
```

### 附加截图

<img width="559" alt="Screenshot 2024-10-26 at 13 24 51" src="https://github.com/user-attachments/assets/4b9ea742-485e-4309-b82f-9d750bf1a14f">

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Temp314159** [comment]
同样遇到该问题，应该与系统无关，windows未发生更新也出现该问题，其它版本号完全一致。

**Comment by jamxe** [comment]
same problem

**Comment by Temp314159** [comment]
补充：根据 #4476 进行排查，包括重装脚本、重装 Tampermonkey 、检查与脚本安装源的网络连接、开启扩展的开发者模式、关闭所有其它扩展，仍然毫无效果。怀疑与 Chrome 的更新有关。不知是否还有其他排查方法……

**Comment by shimakotodo** [comment]
win10的也完全无法启用。
